### PR TITLE
Explicitly delete device-converted tensors.

### LINKED ISSUE #4: Training: CUDA: Out of Memory Optimizations
Hi,
A wonderful paper and thanks for providing the implementation, so that one could reproduce the results.

I have tried training the privileged agent using the script, as mentioned in the README 
**_python train_birdview.py --dataset_dir=../data/sample --log_dir=../logs/sample_** 

I get a _Runtime Error : Tried to allocate 144.00 MiB (GPU 0; 10.73 GiB total capacity; 9.77 GiB already allocated; 74.62 MiB free; 69.10 MiB cached)._ followed by a _ConnectionResetError_

I tried tracing back the error using nvidia-smi and found that the memory usage quickly builds up ( reaching the maximum) before the training begins.

Any leads and suggestions are much appreciated.
Thanks

Attaching the full stack trace  for further reference
stack

### PR DESCRIPTION
**Pull request by tomcur**
Fixes https://github.com/dianchen96/LearningByCheating/issues/4.

### CODE REVIEW

**Comment by dotchen** [comment]
I don't think this is a fix as the python garbage collector would automatically handle this.

**Comment by tomcur** [comment]
The garbage collector does not handle this, as the objects live at least until the variables fall out of scope or are reassigned. A for-loop doesn't create a new scope. That means in the current code memory usage of input tensors is doubled.

More information here: https://github.com/dianchen96/LearningByCheating/issues/4#issuecomment-615429508

**Comment by dotchen** [comment]
This would not be an issue unless your GPU does not have the mem to hold 2x of the data, no? A standard deep learning GPU (1080Ti/Titan) would be able to handle the default batch-size.

**Comment by tomcur** [comment]
That's right; it's likely only an issue when trying the code on simple development machines. Do note that `train_birdview.py`, for the code's default batch size of 256, "wastes" 3GB vmem. It's good practice to `del` tensors when you no longer need them.

**Pull request closed without merging**
